# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
name: hypersloth
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - jupyter
  - jupyterlab
  - ipython
  - ipdb
  - pyyaml
  - tqdm
  - requests
  - pillow
  - sympy
  - networkx
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::pytorch-cuda=12.1 
  - pip:
    - accelerate>=1.7.0
    - transformers>=4.51.0
    - datasets>=3.6.0
    - peft>=0.15.0
    - trl>=0.15.0
    - bitsandbytes>=0.46.0
    - unsloth>=2025.5.0
    - unsloth-zoo>=2025.5.0
    - xformers>=0.0.30
    - diffusers>=0.33.0
    - safetensors>=0.5.0
    - tokenizers>=0.21.0
    - sentencepiece>=0.2.0
    - huggingface-hub>=0.32.0
    - hf-transfer>=0.1.9
    - fastapi
    - pydantic>=2.11.0
    - loguru>=0.7.0
    - tyro>=0.9.0
    - rich>=14.0.0
    - aiohttp>=3.12.0
    - httpx>=0.28.0
    - tensorboard>=2.19.0
    - speedy-utils>=0.1.30
    - cut-cross-entropy>=25.1.0
    - msgspec>=0.19.0
    - json-repair>=0.40.0
    - tabulate>=0.9.0
    - bump2version>=1.0.0
    - freezegun>=1.5.0
    - typeguard>=4.4.0
    - docstring-parser>=0.16
    - overrides>=7.7.0
    - shtab>=1.7.0
    - xxhash>=3.5.0
