[project]
name = "HyperSloth"
version = "0.1.0"
description = ""
authors = [{ name = "anhvth", email = "anhvth.226@gmail.com" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["pyyaml (>=6.0.2,<7.0.0)", "jupyterlab (>=4.3.5,<5.0.0)"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "HyperSloth"
version = "0.1.0"
packages = [
    { include = "HyperSloth" }
]

[tool.poetry.scripts]
hypersloth-cli = "HyperSloth.scripts.hypersloth:main"
hypersloth-prepare-unsloth-model = "HyperSloth.scripts.prepare_model:main"
sim-vllm = "HyperSloth.scripts.vllm_serve:main"
merge_and_save_lora = "HyperSloth.scripts.merge_and_save_lora:main"
# hypersloth-init = "HyperSloth.scripts.hypersloth:init"