model: MODEL_NAME
gpus: 0,1,2,3
host_port: localhost:8150
base_model: ''
loras: lora_name:lora_path,lora_name2:lora_path2
eager: true
served_model_name: null

#==== Extra config
gpu_memory_utilization: 0.9
dtype: auto
max_model_len: 8192
enable_lora: false
bnb: false
not_verbose: false
vllm_binary: null
pipeline_parallel: 1
extra_args: null
lora_modules: null
