# Example configuration file - can be loaded with Fire CLI

file: ./data/cod_6k5.json
packing: false
model_name: unsloth/DeepSeek-R1-Distill-Qwen-7B-unsloth-bnb-4bit
test_ratio: 0.05
max_seq_length: 2048
loss_type: target_only
grad_dir: /dev/shm/hypersloth
